# Generated by Django 5.2.13 on 2026-07-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_alter_actor_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(blank=True, choices=[('USA', 'Estados Unidos'), ('BR', 'Brasil'), ('ARG', 'Argentina'), ('AUS', 'Autrália'), ('BEL', 'Bélgica')], max_length=100, null=True),
        ),
    ]
