# Generated by Django 5.2.13 on 2026-07-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
